"""empty message

Revision ID: 2de6be72033b
Revises: 3e23703c0d00
Create Date: 2025-01-08 13:53:02.098161

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2de6be72033b'
down_revision = '3e23703c0d00'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('planets', schema=None) as batch_op:
        batch_op.alter_column('climate',
               existing_type=sa.VARCHAR(length=120),
               type_=sa.Text(),
               existing_nullable=True)
        batch_op.alter_column('terrain',
               existing_type=sa.VARCHAR(length=120),
               type_=sa.Text(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('planets', schema=None) as batch_op:
        batch_op.alter_column('terrain',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=120),
               existing_nullable=True)
        batch_op.alter_column('climate',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=120),
               existing_nullable=True)

    # ### end Alembic commands ###
